spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: chatdb
      port: 27017
#      username: xxxx
#      password: xxxx
    redis:
      repositories:
        enabled: false
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password: 123456
logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
socketio:
  port: 9999
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 10000
  pingTimeout: 60000
  pingInterval: 25000
  maxHttpContentLength: 1448576
  maxFramePayloadLength: 1448576
server:
  servlet:
    context-path: /chat
  port: 5555
  ssl:
    enabled: false  # 禁用 SSL

minio:
  endpoint: http://localhost:9005  # Windows本地MinIO地址
  fileHost: http://localhost:9005
  access-key: admin           # 访问密钥
  secret-key: admin123456          # 密钥
  bucket-name: chatserver          # 存储桶名称
  secure: false                    # 是否使用HTTPS
  expire: 3600                     # 链接过期时间(秒)